version: '2.1'
########## SERVICES ########
services:
###### xshokacmehttp
  xshokacmehttp:
    image: extremeshok/acme-http2https:latest
    environment:
      - TZ=UTC
      - ACME_DOMAINS=somedomain.com;nws.domain.com,nws-a.domain.com
      - ACME_RESTART_CONTAINERS=xshok_baseimagealpine_1;xshok_baseimagealpine_2;xshok_baseimagealpine_3
      - SKIP_IP_CHECK=no
      - SMTP_HOST=smtp.domain.com
      - SMTP_USER=user@domain.com
      - SMTP_PASS=securepass
      - NOTIFY=admin@domain.com
      - GENERATE_DHPARAM=yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - vol-acme:/acme/:rw
      - vol-certificates:/certs/:rw
    ports:
      - 80:80
    restart: always
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${SYSCTL_IPV6_DISABLED:-0}
